---
# get-your-vpn-ss

- name: create directory
  ansible.builtin.file:
    path: "{{ base_path }}/get-your-vpn-ss"
    state: directory
    mode: '0755'

- name: create config
  copy: src=config.yml dest="{{ base_path }}/get-your-vpn-ss/config.yml"

- name: prepare docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/get-your-vpn-ss/docker-compose.yml"

- name: run get-your-vpn-ss
  become: true
  docker_compose:
    project_src: "{{ base_path }}/get-your-vpn-ss"
    build: no
    files:
    - docker-compose.yml
