---
# get-your-vpn-openvpn-prometheus-exporter

- name: create directory
  ansible.builtin.file:
    path: "{{ base_path }}/get-your-vpn-openvpn-prometheus-exporter"
    state: directory
    mode: '0755'

- name: prepare docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/get-your-vpn-openvpn-prometheus-exporter/docker-compose.yml"

- name: run get-your-vpn-openvpn-prometheus-exporter
  docker_compose:
    project_src: "{{ base_path }}/get-your-vpn-openvpn-prometheus-exporter"
    build: no
    files:
    - docker-compose.yml
