---
# get-your-vpn-config

- name: create directory
  ansible.builtin.file:
    path: /opt/get-your-vpn/get-your-vpn-config
    state: directory
    mode: '0755'

- name: prepare config
  template:
    src: config.ini.j2
    dest: /opt/get-your-vpn/get-your-vpn-config/config.ini

- name: prepare docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/get-your-vpn/get-your-vpn-config/docker-compose.yml

- name: create empty sqlite file
  ansible.builtin.file:
    path: /opt/get-your-vpn/get-your-vpn-config/get-your-vpn-config.sqlite3
    state: touch
    mode: '0755'

# use files parameter to use multiple docker-compose.yml files
- name: run get-your-vpn-config
  docker_compose:
    project_src: /opt/get-your-vpn/get-your-vpn-config
    build: no
    files:
    - docker-compose.yml
