---
# get-your-vpn-openvpn

- name: create directory
  ansible.builtin.file:
    path: "{{ base_path }}//get-your-vpn-openvpn"
    state: directory
    mode: '0755'

- name: create openvpn data directory
  ansible.builtin.file:
    path: "{{ base_path }}//get-your-vpn-openvpn/openvpn-data/conf"
    state: directory
    mode: '0755'

- name: create status log file
  ansible.builtin.file:
    path: "{{ base_path }}/get-your-vpn-openvpn/openvpn-data/openvpn-status.log"
    state: touch
    mode: '0755'

- name: prepare config
  template:
    src: config.yml.j2
    dest: "{{ base_path }}/get-your-vpn-openvpn/config.yml"

- name: prepare docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/get-your-vpn-openvpn/docker-compose.yml"

- name: run get-your-vpn-openvpn
  docker_compose:
    project_src: "{{ base_path }}/get-your-vpn-openvpn"
    build: no
    files:
    - docker-compose.yml
